import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryContext from "./context/QueryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryContext>
          <main className="min-h-screen flex justify-center dark:bg-gray-950 dark:text-white">
            {children}
          </main>
        </QueryContext>
      </body>
    </html>
  );
}
