import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryContext from "./context/QueryContext";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Is This a Cover? - AI Music Analyzer</title>
        <meta name="title" content="Is This a Cover? - AI Music Analyzer" />
        <meta
          name="description"
          content="Is this the original artist or did someone else do it first? Find out now!"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://isthisacover.vercel.app" />
        <meta
          property="og:title"
          content="Is This a Cover? - AI Music Analyzer"
        />
        <meta
          property="og:description"
          content="Is this the original artist or did someone else do it first? Find out now!"
        />
        <meta property="og:image" content="https://i.imgur.com/oUwiPYY.png" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://isthisacover.vercel.app"
        />
        <meta
          property="twitter:title"
          content="Is This a Cover? - AI Music Analyzer"
        />
        <meta
          property="twitter:description"
          content="Is this the original artist or did someone else do it first? Find out now!"
        />
        <meta
          property="twitter:image"
          content="https://i.imgur.com/oUwiPYY.png"
        />

        {/* <!-- Meta Tags Generated with https://metatags.io --> */}
      </head>
      <body className={inter.className}>
        <QueryContext>
          <main className="h-screen w-screen flex flex-col bg-gradient-to-b from-gray-800 to-gray-950 text-white">
            <header className="p-4 flex justify-center">
              <Link href="/" className="flex">
                <div className="text-3xl mr-1">IsThisACover?</div>
                <div>beta</div>
              </Link>
            </header>
            <div className="grow overflow-y-scroll">{children}</div>
          </main>
        </QueryContext>
      </body>
    </html>
  );
}
